use ExtUtils::MakeMaker;

#
# Makefile to install the P.A.T.H. modules
#
# Programmed by Bastian Ballmann
# Last update: 05.01.2004
# 
# This program is free software; you can redistribute 
# it and/or modify it under the terms of the 
# GNU General Public License version 2 as published 
# by the Free Software Foundation.
#
# This program is distributed in the hope that it will 
# be useful, but WITHOUT ANY WARRANTY; without even 
# the implied warranty of MERCHANTABILITY or FITNESS 
# FOR A PARTICULAR PURPOSE. 
# See the GNU General Public License for more details. 

WriteMakefile(
              NAME => 'path::hijack',
              VERSION => '1.0',
              AUTHOR => 'Bastian Ballmann and Stefan Krecher'
              );
